sqlexpressmvc/Models/UpdateVolume.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace sqlexpressmvc.Models
{
    public class UpdateVolume
    {
        [Key]
        public int UpdateVolumeID { get; set; }

        [Required]
        public int EmployeesID { get; set; }
        public virtual Employees Employee { get; set; }

        [Required]
        public int UsedProductsID { get; set; }
        public virtual UsedProducts UsedProducts { get; set; }

        [Required]
        public int newVolume { get; set; }
        
        [ScaffoldColumn(false)]
        public DateTime dateUpdated { get; set; }

    }
}

sqlexpressmvc/Models/UsedProducts.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace sqlexpressmvc.Models
{
    public class UsedProducts
    {
     
        [Key]

        public int UsedProductsID { get; set; }

        [Required]

        public int StockID { get; set; }
        public virtual Stock Stock { get; set; }

        /// <summary>
        /// Validation Disabled as by defaul only qty will be allowed to be used.
        /// </summary>
       // [Remote("ValidateNewQty", "UsedProducts",AdditionalFields ="StockID",ErrorMessage ="Not Valid")]
        public int Usedqty { get; set; }

        [Required]
        public int EmployeesID { get; set; }
        public virtual Employees Employeee { get; set; }


        public int Usedvolume { get; set; }

        public DateTime? dateAdded { get; set; }
        public DateTime? dateModified { get; set; }

    }
}

sqlexpressmvc/Controllers/UsedProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using sqlexpressmvc.Models;

namespace sqlexpressmvc.Controllers
{
    public class UsedProductsController : Controller
    {
        private SalonContext db = new SalonContext();

        // GET: UsedProducts
        public ActionResult Index()
        {
            var usedProducts = db.UsedProducts.Include(u => u.Stock).Include(u=>u.Employeee);
            return View(usedProducts.ToList());
        }

        // GET: UsedProducts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UsedProducts usedProducts = db.UsedProducts.Find(id);
            if (usedProducts == null)
            {
                return HttpNotFound();
            }
            return View(usedProducts);
        }

        // GET: UsedProducts/Create
        public ActionResult Create()
        {

            //Check if Qty is already 0 and skip that item from list
            var stockdata = db.Stocks.Where(s => s.qty > 0);

            ViewBag.StockID = new SelectList(stockdata, "StockID", "Title");
            ViewBag.EmployeesID = new SelectList(db.Employees, "EmployeesID", "FullName");

            return View();
        }

        // POST: UsedProducts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude  = "Usedqty,Usedvolume,dateAdded,dateModified")] UsedProducts usedProducts)
        {
            var ogStock = db.Stocks.Find(usedProducts.StockID);
            if (ModelState.IsValid)
            {
                usedProducts.Usedvolume = ogStock.volume;
                usedProducts.Usedqty = 1;
                ogStock.qty = ogStock.qty -1;                
                db.Entry(ogStock).State = EntityState.Modified;                
                usedProducts.dateAdded = DateTime.Now;
                usedProducts.dateModified = new DateTime();
                db.UsedProducts.Add(usedProducts);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.StockID = new SelectList(db.Stocks, "StockID", "Title", usedProducts.StockID);
            ViewBag.EmployeesID = new SelectList(db.Employees, "EmployeesID", "FullName", usedProducts.EmployeesID);
            return View(usedProducts);
        }


        /// <summary>
        /// Validation Disabled as by defaul only qty will be allowed to be used.
        /// </summary>
        //[OutputCache(Location = System.Web.UI.OutputCacheLocation.None, NoStore = true)]
        //public ActionResult ValidateNewQty(int? Usedqty, int? StockID)
        //{            
        //    var stockqty = db.Stocks.Find(StockID).qty;
        //    var nqty = (int)Usedqty;

        //  if (nqty >= 1 && nqty <= stockqty)
        //    {
        //        return Json(true, JsonRequestBehavior.AllowGet);
        //    }
        //    else
        //    {
        //        return Json(false, JsonRequestBehavior.AllowGet);
        //    }

           
        //}


        // GET: UsedProducts/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    UsedProducts usedProducts = db.UsedProducts.Find(id);
        //    if (usedProducts == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.StockID = new SelectList(db.Stocks, "StockID", "Title", usedProducts.StockID);
        //    return View(usedProducts);
        //}

        //// POST: UsedProducts/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "UsedProductsID,StockID,Usedqty,Usedvolume,dateAdded,dateModified")] UsedProducts usedProducts)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(usedProducts).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.StockID = new SelectList(db.Stocks, "StockID", "Title", usedProducts.StockID);
        //    return View(usedProducts);
        //}

        // GET: UsedProducts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UsedProducts usedProducts = db.UsedProducts.Find(id);
            if (usedProducts == null)
            {
                return HttpNotFound();
            }
            return View(usedProducts);
        }

        // POST: UsedProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UsedProducts usedProducts = db.UsedProducts.Find(id);
            db.UsedProducts.Remove(usedProducts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UpdateVolume(int? id)
        {
            ViewBag.EmployeesID = db.Employees.ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UsedProducts stock = db.UsedProducts.Find(id);
            if (stock == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeesID = new SelectList(db.Employees, "EmployeesID", "FullName", stock.EmployeesID);
            return View(stock);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateVolume([Bind(Exclude = "dateModified")] UsedProducts stock, string newVolume)
        {
            ////TODO : Add Validation to prevent negative values to be updated
            ViewBag.EmployeesID = new SelectList(db.Employees, "EmployeesID", "FullName", stock.EmployeesID);
            int s = int.Parse(newVolume);

            //if (!(newVolume == null))
            //{
            //    s= (int)newVolume;
            //}
            if (ModelState.IsValid)
            {
                if (s <= 0)
                {
                    return Content("<script language='javascript' type='text/javascript'>alert('Couldnt update Volume as new Volume is 0 ! Go Back and try Agains!');</script>");
                }
                else
                if (s > stock.Usedvolume)
                {
                    return Content("<script language='javascript' type='text/javascript'>alert('Couldnt update Volume as new Volume is Greater than Current Volume ! Go Back and try Agains!');</script>");
                }
                else
                {
                    stock.dateModified = DateTime.Now;
                    stock.Usedvolume = stock.Usedvolume - s;
                    db.Entry(stock).State = EntityState.Modified;

                    var newupdtmdl = new UpdateVolume();
                    newupdtmdl.dateUpdated = DateTime.Now;
                    newupdtmdl.EmployeesID = stock.EmployeesID;
                    newupdtmdl.newVolume = s;
                    newupdtmdl.UsedProductsID = stock.UsedProductsID;
                    newupdtmdl.Employee = db.Employees.Find(stock.EmployeesID);
                    newupdtmdl.UsedProducts = db.UsedProducts.Find(stock.UsedProductsID);

                    db.UpdateVolume.Add(newupdtmdl);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(stock);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

sqlexpressmvc/Views/UsedProducts/Create.cshtml
@model sqlexpressmvc.Models.UsedProducts

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UsedProducts</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model=>model.Usedvolume)
        <div class="form-group">
            @Html.LabelFor(model => model.StockID, "EmployeesID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeesID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StockID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StockID, "StockID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StockID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StockID, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Usedqty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Usedqty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Usedqty, "", new { @class = "text-danger" })
            </div>
        </div>*@    
         

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

sqlexpressmvc/Views/UsedProducts/Delete.cshtml
@model sqlexpressmvc.Models.UsedProducts

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UsedProducts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Stock.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stock.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usedqty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usedqty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usedvolume)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usedvolume)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateAdded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateModified)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

sqlexpressmvc/Views/UsedProducts/Details.cshtml
@model sqlexpressmvc.Models.UsedProducts

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>UsedProducts</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Stock.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stock.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usedqty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usedqty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usedvolume)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usedvolume)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateAdded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateModified)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UsedProductsID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

sqlexpressmvc/Views/UsedProducts/Edit.cshtml
@model sqlexpressmvc.Models.UsedProducts

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UsedProducts</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UsedProductsID)

        <div class="form-group">
            @Html.LabelFor(model => model.StockID, "StockID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("StockID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StockID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Usedqty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Usedqty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Usedqty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Usedvolume, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Usedvolume, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Usedvolume, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateAdded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateAdded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateAdded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dateModified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dateModified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dateModified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

sqlexpressmvc/Views/UsedProducts/Index.cshtml
@model IEnumerable<sqlexpressmvc.Models.UsedProducts>

@{
    ViewBag.Title = "In-Use Products";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @Styles.Render("~/Content/datatablecss")
}

<h4><span class="glyphicon glyphicon-th-list"></span> In-Use Products</h4>

<p>
    @Html.ActionLink("Create New", "Create",null, new { @class="btn btn-primary"})
</p>

<table class="table-fill">
    <thead>
        <tr>
            <th  class="text-left">
                Stock
            </th>
            <th class="text-left">
                Quantity
            </th >
            <th class="text-left">
                Volume
            </th>
            <th class="text-left">
                Date Opened
            </th>
            <th class="text-left">
                Last Used
            </th>
            <th class="text-left">
                Actions
            </th>
        </tr>
    </thead>
    <tbody class="table-hover">
        @foreach (var item in Model)
        {
            <tr>
                <td class="text-left">
                    @Html.DisplayFor(modelItem => item.Stock.Title)
                </td>
                <td class="text-left">
                    @Html.DisplayFor(modelItem => item.Usedqty)
                </td>
                <td class="text-left">
                    @Html.DisplayFor(modelItem => item.Usedvolume)
                </td>
                <td class="text-left">
                    @Html.DisplayFor(modelItem => item.dateAdded)
                </td>
                <td class="text-left">
                    @Html.DisplayFor(modelItem => item.dateModified)
                </td>
                <td class="text-left">
                    @Html.ActionLink("Edit", "Edit", new { id = item.UsedProductsID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.UsedProductsID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.UsedProductsID })|
                    @Html.ActionLink("UpdateVolume", "UpdateVolume", new { id = item.UsedProductsID })
                </td>
            </tr>
        }
    </tbody>
</table>

sqlexpressmvc/Views/UsedProducts/UpdateVolume.cshtml
@model sqlexpressmvc.Models.UsedProducts

@{
    ViewBag.Title = "UpdateVolume";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Update Volume</h4>
<hr />
@using (Html.BeginForm("UpdateVolume", "UsedProducts", FormMethod.Post, new { newVolume = ViewBag.newVolume }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">   
       
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UsedProductsID)
        @Html.HiddenFor(model => model.StockID)
        @*//@Html.HiddenFor(model => model.EmployeesID)*@
        @Html.HiddenFor(model => model.Usedqty)  
        @Html.HiddenFor(model => model.Usedvolume)
        @Html.HiddenFor(model => model.dateAdded)
                   

        <div class="col-lg-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    @Html.DisplayFor(model => model.Stock.FullName)
                </div>

                <div class="panel-body">
                    <div class="form-group">
                        @Html.LabelFor(model => model.EmployeesID, "EmployeesID", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("EmployeesID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.EmployeesID, "", new { @class = "text-danger" })
                        </div>
                    </div> 
                    <div class="form-control">
                        Current Volume : @Html.DisplayFor(model => model.Usedvolume)
                    </div>
                    <div class="form-control">
                        Update Volume : @Html.TextBox("newVolume")<br />
                    </div>
                </div>
                <div class="panel-footer">
                    <input type="submit" value="Save" class="btn btn-danger" />
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning" })
                </div>
            </div>
        </div>

 
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}