sqlexpressmvc/Models/RateList.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace sqlexpressmvc.Models
{
    public class RateList
    {
        public RateList()
        {
            this.Billings = new HashSet<Billing>();
        }
        [Key]
        public int RateListID { get; set; }
       
        [Display(Name = "Name")]
        [Required(AllowEmptyStrings = false)]
        public string Title { get; set; }

        [Display(Name = "Price")]
        [DataType(DataType.Currency)]
        [Required]
        public float price { get; set; }
        
        [Display(Name = "Added on")]
        [DataType(DataType.DateTime)]
        public DateTime? dateAdded { get; set; }

        [ScaffoldColumn(false)]
        [Display(Name = "Modified on")]
        [DataType(DataType.DateTime)]
        public DateTime? dateModified { get; set; }

        public virtual ICollection<Billing> Billings { get; set; }
        public virtual String FullName { get { return Title + "- [" + price+"]"; } }
    }
}

sqlexpressmvc/Controllers/RateListsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using sqlexpressmvc.Models;
using PagedList.Mvc;
using PagedList;

namespace sqlexpressmvc.Controllers
{
    public class RateListsController : Controller
    {

        private SalonContext db = new SalonContext();

        // GET: RateLists
        public ActionResult Index(string searchString, string currentFilter, string sortOrder, int? page)
        {
            var Result = from s in db.RateLists
                         select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                Result = Result.Where(s => s.Title.Contains(searchString));
            }

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            switch (sortOrder)
            {
                case "name_desc":
                    Result = Result.OrderByDescending(s => s.Title);
                    break;
                case "Date":
                    Result = Result.OrderBy(s => s.dateAdded);
                    break;
                case "date_dsc":
                    Result = Result.OrderByDescending(s => s.dateAdded);
                    break;
                default:
                    Result = Result.OrderBy(s => s.Title);
                    break;
            }

            int pageSize = 20;
            int pageNumber = (page ?? 1);

            return View(Result.ToPagedList(pageNumber, pageSize));
        }

        // GET: RateLists/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RateList rateList = db.RateLists.Find(id);
            if (rateList == null)
            {
                return HttpNotFound();
            }
            return View(rateList);
        }

        //public ActionResult SearchByMobile(string mobile)
        //{
        //}
        // GET: RateLists/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RateLists/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude = "dateAdded,dateModified")] RateList rateList)
        {
            if (ModelState.IsValid)
            {
                rateList.dateAdded = DateTime.Now;
                rateList.dateModified = new DateTime();
                db.RateLists.Add(rateList);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rateList);
        }

        // GET: RateLists/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RateList rateList = db.RateLists.Find(id);
            if (rateList == null)
            {
                return HttpNotFound();
            }
            return View(rateList);
        }

        // POST: RateLists/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Exclude ="dateModified")] RateList rateList)
        {
            if (ModelState.IsValid)
            {
                rateList.dateModified = DateTime.Now;
                db.Entry(rateList).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(rateList);
        }

        //// GET: RateLists/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    RateList rateList = db.RateLists.Find(id);
        //    if (rateList == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(rateList);
        //}

        //// POST: RateLists/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    RateList rateList = db.RateLists.Find(id);
        //    db.RateLists.Remove(rateList);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

sqlexpressmvc/Views/RateLists/Create.cshtml
@model sqlexpressmvc.Models.RateList

@{
    ViewBag.Title = "Create Services";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Service</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

sqlexpressmvc/Views/RateLists/Details.cshtml
@model sqlexpressmvc.Models.RateList

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateAdded)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.dateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateModified)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RateListID }) |
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning" })
</p>

sqlexpressmvc/Views/RateLists/Edit.cshtml
@model sqlexpressmvc.Models.RateList

@{
    ViewBag.Title = "Edit Services";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="col-lg-5">
        <div class="panel panel-success">
            <div class="panel-heading">Edit Service</div>
            <div class="panel-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.RateListID)
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div><br />
                <div class="form-group">
                    @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.HiddenFor(model => model.dateAdded);
                        </div>
            <div class="panel-footer">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-warning" })

            </div>
        </div>
    </div>

}

<div>
   
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

sqlexpressmvc/Views/RateLists/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<sqlexpressmvc.Models.RateList>

@{
    ViewBag.Title = "Services";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @Styles.Render("~/Content/datatablecss")

}   <h4>@Html.Label("Options")</h4>

@using (Html.BeginForm("Index", "RateLists", FormMethod.Get))
{<div class="panel panel-info">
        <div class="panel-body">
            <div>
                @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
                <div class="col-lg-3">
                    <div class="input-group">
                        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control" })
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i> Search</button>
                        </span>
                    </div>
                </div>

                @Html.Label("Filter By", new { @class = "label label-info" })
                @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.FNAMESPM, currentFilter = ViewBag.CurrentFilter }, new { @class = "label label-default" })
                <span class="glyphicon glyphicon-sort-by-alphabet"></span>
                @Html.ActionLink("Date Added", "Index", new { sortOrder = ViewBag.DATEADDEDSPM, currentFilter = ViewBag.CurrentFilter }, new { @class = "label label-default" })
                <span class="glyphicon glyphicon-sort-by-alphabet"></span>

            </div>
    </div>
</div>

} 
<h4><span class="glyphicon glyphicon-th-list"></span> @Html.Label("List of Services")</h4>
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
<table class="table-fill">
    <thead>
        <tr>
            
            <th class="text-left">@Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })<span class="glyphicon glyphicon-sort"></span></th>            
            <th class="text-left">Price</th>           
            <th class="text-left">@Html.ActionLink("Date Modified", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter }) <span class="glyphicon glyphicon-sort"></span></th>
            <th class="text-left">Actions</th>
        </tr>
    </thead>
    <tbody class="table-hover">
       
         @foreach (var item in Model)
         {
            <tr onclick="location.href = '@(Url.Action("Details", "RateLists",new { id = item.RateListID }))'">
                <td class="text-left">
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td class="text-left">
                    @Html.DisplayFor(modelItem => item.price)
                </td>
                <td class="text-left">
                    @Html.DisplayFor(modelItem => item.dateModified)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.RateListID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.RateListID })
                </td>
            </tr>
         }
</table>
  
    
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
@*
    @foreach (var item in Model)
    {
    <div class="col-lg-3">
        <div class="panel panel-info ">
            <div class="panel-body">
                <span class="label label-success">Name</span> @Html.DisplayFor(modelItem => item.Title)<br />
                <span class="label label-success">Price:</span> @Html.DisplayFor(modelItem => item.price)<br />
                <span class="label label-success">Created:</span> @Html.DisplayFor(modelItem => item.dateAdded)<br />
                    <span class="label label-success">Modified:</span> @Html.DisplayFor(modelItem => item.dateModified)<br /><br />
            </div>
            <div class="panel-footer">
                @Html.ActionLink("Edit", "Edit", new { id = item.RateListID }, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
    }*@